export const IGNORED_PROPS_META_KEY = 'IGNORED_PROPS_META_KEY';
export const LABEL_META_KEY = 'LABEL_META_KEY';
export const POSITION_META_KEY = 'POSITION_META_KEY';
export const IDENTITY_META_KEY = 'IDENTITY_META_KEY';
export const FORMAT_META_KEY = 'FORMAT_META_KEY';
